title: DataConnectIL
description: G

username: DataConnectIL
user_description: A
user_title: B
email: maya.fudim@datahack.org.il
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
facebook_username: datahackil
linkedin_username: datahack
github_username:  DataHackIL
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']
