title: DataConnectIL
description: "At DataConnectIL, we are bringing together the incredible global talent that has recently arrived in Israel and connecting them with the local and the global Tech ecosystem."

username: DataConnectIL
user_description: "A professional AI & Cyber Security community"
user_title: "Talent is universal, but opportunity depends on the right network."
email: maya.fudim@datahack.org.il
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
facebook_username: datahackil
linkedin_username: datahack
# github_username:  DataHackIL
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']
